"""make full_name, last_used_at, expires_at nullable

Revision ID: 0e76339824f4
Revises: 0455c6e66a99
Create Date: 2026-07-16 10:36:18.315086
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0e76339824f4'
down_revision: Union[str, None] = '0455c6e66a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('key_prefix',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('request_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rate_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.alter_column('api_key_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('status_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('response_time',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('request_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('response_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('meta_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('face_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_vector', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('embedding')
        batch_op.drop_column('enrolled_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_verified')

    with op.batch_alter_table('liveness_logs', schema=None) as batch_op:
        batch_op.alter_column('verification_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('check_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('frame_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('duration_ms',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('meta_data',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('monthly_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('meta_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.alter_column('api_key_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('api_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('processing_time',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('checks_performed',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('spoof_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('deepfake_risk',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('deepfake_risk',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('spoof_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('checks_performed',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('processing_time',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('api_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('api_key_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('meta_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('monthly_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('liveness_logs', schema=None) as batch_op:
        batch_op.alter_column('meta_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('duration_ms',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('frame_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('check_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('verification_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('face_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_verified', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('enrolled_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sqlite.JSON(), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('embedding_vector')

    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('meta_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('resource_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('response_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('request_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('response_time',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('endpoint',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('api_key_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('rate_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('request_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('key_prefix',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('face_enrollments')
    # ### end Alembic commands ###
