"""Add face profile metadata columns

Revision ID: ae0ddd06aae8
Revises: 3136a9b55ec6
Create Date: 2026-08-21 12:34:05.802570
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0ddd06aae8'
down_revision: Union[str, None] = '3136a9b55ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_embedding', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('embedding_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('template_version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('template_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')
        batch_op.drop_column('template_metadata')
        batch_op.drop_column('template_version')
        batch_op.drop_column('embedding_hash')
        batch_op.drop_column('original_embedding')

    # ### end Alembic commands ###
