[alembic]
script_location = alembic
sqlalchemy.url = sqlite:///./mitra_verify.db

[log]
level = INFO
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
